ALTER TRIGGER TG_ESTORNO_ESTOQUE
   ON VENDAS
       FOR DELETE
AS
    BEGIN
        DECLARE
    @CODIGO	INT,
    @QTDE	INT
       SELECT @CODIGO = CODIGO, @QTDE = QTDE FROM DELETED
    UPDATE ESTOQUE   -- Atualiza a quantidade na tabela ESTOQUE
	SET QTDE = QTDE +  @QTDE
	WHERE CODIGO = @CODIGO
    END


 ALTER TRIGGER TG_ESTORNO_CAIXA
   ON VENDAS
       FOR DELETE
AS
    BEGIN
        DECLARE
    @VALOR	DECIMAL(10,2),
    @DATA	DATE,
	@QTDE INT
       SELECT @DATA = DATA, @VALOR = VALOR, @QTDE=QTDE FROM DELETED
       UPDATE CAIXA 
	SET SALDO_FINAL = SALDO_FINAL - (@VALOR * @QTDE)
	WHERE DATA = @DATA
    END